_BASE_: "../../Base-RetinaNet.yaml"

MODEL:
    META_ARCHITECTURE: "ProbabilisticRetinaNet"

    WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

    RESNETS:
      DEPTH: 50

    RETINANET:
        NUM_CLASSES: 80

DATALOADER:
    NUM_WORKERS: 8  # 2x number of GPUs used for training/validation

SOLVER:
    IMS_PER_BATCH: 4
    BASE_LR: 0.0025  # Note that RetinaNet uses a different default learning rate
    STEPS: (210000, 250000)
    MAX_ITER: 270000

INPUT:
    MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)

DATASETS:
    TRAIN: ("coco_2017_custom_train",)
    TEST: ("coco_2017_custom_val",)

VERSION: 2
