_BASE_: "../../Base-DETR.yaml"

MODEL:
    META_ARCHITECTURE: "ProbabilisticDetr"
    WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl" # For fully reproducible results, replace this line with
                                                             # the path to detr_converted_model_500_epochs.pth,  downloaded from the original detr repo.
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]

SOLVER:
    IMS_PER_BATCH: 16
    BASE_LR: 0.0001
    STEPS: (246400,)
    MAX_ITER: 369600
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 10
    WEIGHT_DECAY: 0.0001
    OPTIMIZER: "ADAMW"
    BACKBONE_MULTIPLIER: 0.1
    CLIP_GRADIENTS:
        ENABLED: True
        CLIP_TYPE: "full_model"
        CLIP_VALUE: 0.01
        NORM_TYPE: 2.0

DATALOADER:
    FILTER_EMPTY_ANNOTATIONS: False
    NUM_WORKERS: 8  # Depends on the available memory

TEST:
  EVAL_PERIOD: 7330  # ~1 epoch

DATASETS:
    TRAIN: ("coco_2017_custom_train",)
    TEST: ("coco_2017_custom_val",)
