_BASE_: "Base-COCO-DETR.yaml"

MODEL:
    PROBABILISTIC_MODELING:
        # One of the following Loss types: 'none' or 'negative_log_likelihood', 'second_moment_matching', 'energy_loss'.
        BBOX_COV_LOSS:
            NAME: 'pmb_negative_log_likelihood'
            COVARIANCE_TYPE: 'diagonal' # One of the following: 'full', 'diagonal'
            DISTRIBUTION_TYPE: 'laplacian'

        MATCHING_DISTANCE: 'euclidian'
        ANNEALING_STEP: 1
        NLL_MAX_NUM_SOLUTIONS: 1

    WEIGHTS: 'path to detr_R_50_reg_var_nll.pth'

SOLVER:
    BASE_LR: 0.00005
    STEPS: (60000, 100000)
    MAX_ITER: 135000