_BASE_: "../../Base-RCNN-FPN.yaml"

MODEL:
    META_ARCHITECTURE: "ProbabilisticGeneralizedRCNN"

    WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"

    RESNETS:
        DEPTH: 50

    ROI_HEADS:
        NAME: "ProbabilisticROIHeads"
        IN_FEATURES: ["p2", "p3", "p4", "p5"]

SOLVER:
    IMS_PER_BATCH: 4
    BASE_LR: 0.005
    STEPS: (210000, 250000)
    MAX_ITER: 270000

DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory

DATASETS:
    TRAIN: ("coco_2017_custom_train",)
    TEST: ("coco_2017_custom_val",)
